# Generated by Django 5.1.7 on 2025-05-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversation_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='processing_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
